### ISSUE TITLE
Internal library for frontend and backend communication

### ISSUE THREAD

**Issue by jkwening** [TheDevPath/Navi#172]
To avoid duplication of code and ease of testing, let's merge `~/client/src/js/utilities.js` into `server-requests-utils.js` and expand as library for handling frontend requests with backend server. We have a few server end points at this moment, so let's organize the frontend requests code into a single location and abstract further if needed to modular pieces.

Please reference `~/routes` and `~/controllers` for details as to the available end points and information needed to get successful response from backend server.

**Comment by shiolovesgod** [comment]
I'm working on a task with frontend-backend communication and find myself in need of these tools to prevent code duplication.  

Currently I'm coding a work-around but would just like to verify that when this component does become functional, the `makeRequest()` method will return a promise.

**Comment by shiolovesgod** [comment]
If it's ok, I'd like to start this off by:
- refactoring `utilities.js` 
- writing the `makeRequest` function
   * I would just need clarification of a few of the function parameters:
      * `endPointAddon` & `params`

This is integral in my current task (getting user's saved locations), and I'm writing a lot of the code for that anyway.

**Comment by jkwening** [comment]
@shiolovesgod sure give it a shot; you're currently working on #183 right? The idea behind `makeRequest` function is to generalize frontend requests to backend without having to expose multiple functions for making request and simplify use by future contributors.

Basically, I'm envisioning a single function that when passed appropriate arguments while build the necessary server request returning a promise for the result. Feel free to modify as needed to implement the logic; what you're seeing was just my initial quick start at implementation before I realized I needed to move onto other priority tasks.

The `endpointAddon` are for passing extensions to the `baseEndPoints` since some have additional URIs that return more specific data. Alternatively, we can just add more keys to `BASE_ENDPOINTS` object if that seems simpler and more appropriate. `params` is for those endpoints that require passed params as part of the URI.

**Comment by shiolovesgod** [comment]
Got it. I'm not sure what the function `postAutocomplete` was supposed to do but it's throwing errors:

1. The library for importing url is not found:
`import { url } from 'inspector';`

2. The variable `url` is already defined so this gives an error:
`return AXIOS_INSTANCE.post(url=BASE_ENDPOINTS.autocomplete, {input});`

**Comment by jkwening** [comment]
you can ignore that function...its incomplete. I would suggest starting with `utilities.js`, add and refactor accordingly as needed to complete #183. Getting that feature implemented is pertinent for the MVP we're trying to deploy this week. Doing that will also build upon completing this ticket.

**Comment by shiolovesgod** [comment]
Pull request created.  #183 should be completed tomorrow using the updated `utilites.js`

**Comment by shiolovesgod** [comment]
@jkwening what else needs to be done to close this task out?

**Comment by jkwening** [comment]
@shiolovesgod I'll try and get back to you tomorrow. One related task, is to refactor existing frontend code that is still directly using `axios` to communicate with the backend server instead of the `makeRequest` function from the library.

**Comment by jkwening** [comment]
Closing issue since complete.

Notes: removed direct `axios` calls with `makeRequest` from existing frontend code. @turisap has code with clearer doc string for `makeRequest` in upcoming PR.
