### ISSUE TITLE
Enhance saved pin feature - Master list

### ISSUE THREAD

**Issue by jkwening** [TheDevPath/Navi#204]
This is an expansion on issue #185 completed in #203. Currently, if user has signed in, user can save a dropped pin to the database. This needs the following enhancements, each can become their own unique issue:
- [x] If not signed in, notify user and give option to sign-in/register and then process the save to db  **high priority**
- in "guest" mode, save to temporarily in pouchDB. Maybe as future feature, if offline with active session re-sync to server db once back online? This will most likely require us to transition to CouchDB on backend.  **low priority**
- [x] Add logic to server to avoid saving duplicate pin locations; update db if needed  **high priority**
- [x] Remove save button on success or if updated in db  **high priority**
- Change alerts to fancier notifications, maybe just a simple toast notification  **mid priority**
- [x] Change pin marker to the style used for saved pins and add to the preloaded layer group **extension of #183** 

- [ ] Add the ability to delete a savedpin

**Comment by shiolovesgod** [comment]
Hey, I think I can take on this issue.  This is what I propose to handle:

* notify user if not signed in
  - I'll use an alert for now, I can code for toast if we implement it
  - Add logic to server to check for pin duplication (based on latlng)
  - Change pin type once it has been saved (favorites style)
 
This is what I won't handle as of right now:
  - Guest mode saves

**Comment by jkwening** [comment]
@shiolovesgod sounds good - assigned to you. Thanks!

**Comment by shiolovesgod** [comment]
@jkwening are we considering exact `lat,lng` to be the same place or is an approximate location (several decimal places) also the same place? 

I'll do exact `lat,lng` unless we decide otherwise.

**Comment by steveone** [comment]
I am just joining the project and notice that every time I click on the map, it auto adds a pin to the map unless I click "remove". I don't think it should be saving the pin but rather should remove any pin you didn't tell it to save or label. Is this the same issue here or a new issue I should open and work on separately?

**Comment by jkwening** [comment]
@steveone I'm not sure I'm following - what you described sounds like expected behavior. Clicking on the map activates "dropped pin" feature. You then have the option to save or remove the pin. It shouldn't save it unless you explicitly click the save button which if successful will turn it into a favorite marker. Are you saying it automatically saves without any additional action?

**Comment by steveone** [comment]
@jkwening what is the expected behavior if you do not click either the "save" or "delete" button. My expectation would be that the pin would disappear (same as hitting delete). I would not expect that a pin would exist everywhere I click on the map.

**Comment by jkwening** [comment]
@steveone oh gotcha - yeah, we should only have a single instance of a "dropped pin" at any given time. You're right clicking else where should move the pin to the new location. Please proceed with creating an issue for this. Thanks for catching the bug.

**Comment by motosharpley** [comment]
closing in favor of specific individual issue
