### ISSUE TITLE
Create a resources for beginners page which will include Github/Git instructions 

### ISSUE THREAD

**Issue by tanyagupta** [TheDevPath/Navi#218]
Do you want to request a feature or report a bug?
Feature

If this is a feature request, what is motivation or use case for changing the behavior?
More guidance for newcomers
If the current behavior is a bug, please provide the steps to reproduce.
na
What is the expected behavior?
na
What is the current behavior?
na
Please mention other relevant information.
na
    Node version
    npm version
    Operating system
    CLI version
    Browser
    Device

**Comment by tanyagupta** [comment]
@jkwening could you assign this to me please ?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by jkwening** [comment]
@tanyagupta done.

**Comment by tanyagupta** [comment]
@jkwening @motosharpley could you please merge ? Can I go ahead and close this out ?
Let me know if you need any changes
thanks!
