### ISSUE TITLE
declare permissions in manifest.json

### ISSUE THREAD

**Issue by motosharpley** [TheDevPath/Navi#247]
we need to add declare permissions to the client>manifest.json file 
see here for details https://developer.chrome.com/apps/declare_permissions

**Comment by roncham** [comment]
I'd like to do this one Bryan. What do we need besides geolocation. storage? notifications?

**Comment by motosharpley** [comment]
Sure @roncham I sent you an invite to the team so that I can assign this to you. The primary issue this currently concerns is geolocation, however there is a lot to be explored on the topic which might be useful to the app.

**Comment by roncham** [comment]
The 'clipboardWrite' permission could be handy for copying directions to paste into messaging or other apps. Would also require some code added though.

clipboardWrite "Indicates the extension or app uses document.execCommand('copy') or document.execCommand('cut'). This permission is required for hosted apps; it's recommended for extensions and packaged apps."
