### ISSUE TITLE
fix search autocomplete geocode

### ISSUE THREAD

**Issue by motosharpley** [TheDevPath/Navi#248]
fix search autocomplete to get user geolocation instead of server

**Comment by khusbuchandra** [comment]
Finally i could get some time to look into the issue and till now my findings have been that GetGeoLocation Api call returns lat & lng values{lat: 39.043756699999996, lng: -77.4874416} from somewhere in VA which is set in Home. If user goes to map from there, it still holds that lat, lng values and shows wrong location.  
Instead if we refresh the map, it reloads with correct location with lat & lng being set correctly. 
In that case the request for /search/autocomplete from client has correct payload as shown in Network, but returns wrong response. Now only way it's possible is if the backend api is somehow using the geolocation data as lat & lng and not the one being passed from client. 
@jkwening, Is there a way to verify what request is being set to google map api from backend?  It's pretty strange as I see the code in autocomplete api just passes what it receives from client, but i might be missing something.
We also need to fix the getGeolocation(/map/geolocation) to not get the server location rather the device /browser location to load the correct user location on map.
