### ISSUE TITLE
add delete to savedpins

### ISSUE THREAD

**Issue by motosharpley** [TheDevPath/Navi#257]
Add delete functionality to frontend savedpins

**Comment by steveone** [comment]
Delete button added but needs CSS updates to look prettier

**Comment by steveone** [comment]
@motosharpley this issue can be closed. There are a few functions duplicated in different locations to create the buttons and text in the markers that should be merged but I think that can be a new issue?

**Comment by jkwening** [comment]
@steveone yes, please create an issue for refactoring to resolve duplication of code as detailed as you can. It will help facilitate maintaining, expanding, and effectively testing the code base. Thanks - will close this issue.
