### ISSUE TITLE
Merge duplicate functions (createLabel, createInput, createButton)

### ISSUE THREAD

**Issue by steveone** [TheDevPath/Navi#268]
Do you want to request a feature or report a bug? 

Duplicate code in multiple files needs moving to a utility file

If this is a feature request, what is motivation or use case for changing the behavior? 

Cleaner more maintainable code and testing

The createLabel, createInput and createButton functions are duplicated (or two of them at least) in the client code in the following files:

- Navi/client/src/components/LeafletOsmMap/index.js 
- Navi/client/src/js/saved-places.js

I propose to move them to a single utility file in the **Navi/client/src/js/** directory. I suggest a new file called marker-display-util.js but am open to suggestions for naming?

Please assign this to me and I will do the merging and see if any tests need updating or adding.

**Comment by jkwening** [comment]
@steveone assigned to you. Thanks.

**Comment by Euklidian-Space** [comment]
@steveone  Sorry to butt into this conversation, but I was wondering what is being used to test the front end components?  I usually see people using enzyme to mount components, but I don't see it as a dev dependency in package.json.

**Comment by steveone** [comment]
@Euklidian-Space It's a good question. I just looked and don't see any front-end tests at all. I did see a api/server test "saved-pins-test.js" that needs updating to include a new field "desc" for saved-pins. I've used Mocha/Chai in the past, I know Jest/Enzyme are the new preferred. I'm open to whatever the team wants.

**Comment by motosharpley** [comment]
@Euklidian-Space @steveone take a look at PR #261 we had originally set up mocha/chai but pr#261 is setting up jest

**Comment by Euklidian-Space** [comment]
@steveone what is the desc field doing exactly?  I don't see it being utilized in the saved-pins-controller at all.

**Comment by steveone** [comment]
@Euklidian-Space , you may need to update you local repo as it was only added 3 days ago (or so).  It's on line 84 based on the current version.
