### ISSUE TITLE
Trailing Commas user-controller.js

### ISSUE THREAD

**Issue by someyoungideas** [TheDevPath/Navi#298]
I was curious if anyone has issues running the app with the trailing commas in `users-controller.js`? If so I have a branch with the fixes, but I was checking first because it seemed like something others may not have issues with in order to run the app. There are three of them in the controller in various locations.

In order to reproduce I am running `npm run dev` script and I am seeing the errors show as `Syntax Error` from nodemon.

Here are my specs:

NodeJS - v6.5.0
NPM - 5.7.1
MacBook Pro
OS X El Capitan

**Comment by someyoungideas** [comment]
It seems like this is an issue with the version of NodeJS being used. I started using `v8.5.0` and everything worked as expected. Maybe there should be a minimum requirements of NodeJS version in the README.md?

**Comment by motosharpley** [comment]
@someyoungideas sorry I didn't get to this sooner, what I would like to do is specify our engine in the package.json we started the project on node v8.9.0 and this is something I need to add for the deployment pipeline anyways. If you want to add this and the debug script in your PR #299 that would be great.
Thanks

**Comment by someyoungideas** [comment]
Closing after merge of #299 PR
